name: juristally
description: A new Flutter project.
auther: Govind Kumar Meena
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  get: ^4.3.8
  provider: ^6.0.0
  pin_code_fields: ^7.3.0
  http: ^0.13.3
  cached_network_image: ^3.1.0
  flutter_typeahead: ^3.2.1
  file_picker: ^4.1.1
  image_cropper: ^1.4.1
  share: ^2.0.4
  intl: ^0.17.0
  infinite_scroll_pagination: ^3.1.0
  socket_io_client: ^1.0.1
  flutter_sound: ^8.3.12
  permission_handler: ^8.1.6
  path_provider: ^2.0.4
  speech_to_text: ^5.1.1
  flutter_pdfview: ^1.2.1
  agora_rtc_engine: ^4.0.7
  substring_highlight: ^1.0.33
  card_swiper : ^1.0.4
  url_launcher: ^6.0.12
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0
  flutter_local_notifications: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/black-logo.png
    - assets/images/white-logo.png
    - assets/images/articles.png
    - assets/images/bare_acts.png
    - assets/images/judgement.png
    - assets/images/legal_updates.png
    - assets/images/library.png
    - assets/images/library_blue.png
    - assets/images/moot.png
    - assets/images/lets_talk.png
    - assets/images/debate.png
    - assets/images/audio_chat.png
    - assets/images/audio_chat_blue.png
    - assets/lang/en.json
    - assets/lang/hi.json



fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Black.ttf
      - asset: fonts/Roboto-BlackItalic.ttf
      - asset: fonts/Roboto-Bold.ttf
      - asset: fonts/Roboto-Roboto-BoldItalic.ttf
      - asset: fonts/Roboto-Italic.ttf
      - asset: fonts/Roboto-Light.ttf
      - asset: fonts/Roboto-LightItalic.ttf
      - asset: fonts/Roboto-Medium.ttf
      - asset: fonts/Roboto-MediumItalic.ttf
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Thin.ttf
      - asset: fonts/Roboto-ThinItalic.ttf


  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  




  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
